config/routes.rb
Rails.application.routes.draw do
  get 'teacher/test'

  get 'teacher/result'

  get 'test/demand'

  get 'test/index'

  get 'test/result'

  get 'signin/index'

  get 'course/video1'

  get 'course/video2'

  get 'home/index'

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  def video1
  end

  def video2
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  def index
  end
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  def test
  end

  def result
  	  @static_item = {
  		"1" => "正确答案",
  		"2" => "正确率",
  		"3" => "作答人数",
  		"4" => "选A人数",
  		"5" => "选B人数",
  		"6" => "选C人数",
  		"7" => "选D人数"
  	}
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end

  def result
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_helper.rb
module CourseHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/course/video1.html.erb
<!--content-->
<div class="container video">
	<div class="row">
		<div class="col-md-7 text-center">
			<video width="99.95%" height="422" class="mejs-player" poster="/assets/01index_video1.png" controls="controls" preload="none">
				<source type="video/mp4" src="http://vjs.zencdn.net/v/oceans.mp4" />
				<source type="video/webm" src="myvideo.webm" />
				<source type="video/ogg" src="myvideo.ogv" />
			</video>
		</div>
		<div class="col-md-5">
			<div class="introduce">
				<h2 class="text-center">网络设备维护基础&nbsp;&nbsp;第一集</h2>
				<h3>课程介绍：</h3>
				<p class="text-justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;移动通信网络组成与主要设备介绍。4G通信技术并没有脱离以前的通信技术，而是以传统通信技术为基础，并利用了一些新的通信技术，来不断提高无线通信的网络效率和功能的。4G通信会是一种超高速无线网络，一种不需要电缆的信息超级高速公路，这种新网络可使电话用户以无线及三维空间虚拟实境连线。</p>
				<h3>讲师：</h3>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;王天义（大唐移动高级工程师，讲师）</p>
			</div>
		</div>
	</div>
	<div class="text-center">
		<%= link_to "本科作业", test_index_path, class: "btn btn-info btn-course", role: "button" %>
		<span>&nbsp;</span>
		<%= link_to "成绩查询", test_demand_path, class: "btn btn-info btn-course", role: "button" %>
	</div>
</div>
<!--video-list-->
<div class="container video-list">
	<div class="list-title">
		<span class="rel">相关课程</span>
	</div>
	<div class="list-body">
		<h4><span class="glyphicon glyphicon-play-circle"></span>&nbsp;&nbsp;&nbsp;&nbsp;网络设备维护基础&nbsp;&nbsp;&nbsp;&nbsp;第2集</h4>
		<hr class="dot">
		<h4><span class="glyphicon glyphicon-play-circle"></span>&nbsp;&nbsp;&nbsp;&nbsp;网络设备维护基础&nbsp;&nbsp;&nbsp;&nbsp;第2集</h4>
		<hr class="dot">
		<h4><span class="glyphicon glyphicon-play-circle"></span>&nbsp;&nbsp;&nbsp;&nbsp;网络设备维护基础&nbsp;&nbsp;&nbsp;&nbsp;第2集</h4>
		<hr class="dot">
		<h4><span class="glyphicon glyphicon-play-circle"></span>&nbsp;&nbsp;&nbsp;&nbsp;网络设备维护基础&nbsp;&nbsp;&nbsp;&nbsp;第2集</h4>
	</div>
</div>

app/views/course/video2.html.erb
<div class="container video">
	<h3><span class="glyphicon glyphicon-play icon-color"></span>&nbsp;&nbsp;正在播放：网络设备维护基础&nbsp;&nbsp;第一集</h3>
	<div class="row">
		<div class="col-md-8">
			<video width="99.96%" height="509" class="mejs-player" poster="/assets/video2.png" controls="controls" preload="none">
				<source type="video/mp4" src="http://vjs.zencdn.net/v/oceans.mp4" />
				<source type="video/webm" src="myvideo.webm" />
				<source type="video/ogg" src="myvideo.ogv" />
			</video>
		</div>
		<div class="col-md-4">
			<div class="knowledge">
				<div class="k-title">知识点</div>
				<div class="catalog">
					<p><span class="glyphicon glyphicon-menu-right icon-color"></span>&nbsp;&nbsp;00:05:00&nbsp;&nbsp; GSM网络结构</p>
					<p><span class="glyphicon glyphicon-menu-right icon-color"></span>&nbsp;&nbsp;00:20:15&nbsp;&nbsp; TD网络结构</p>
					<p><span class="glyphicon glyphicon-menu-right icon-color"></span>&nbsp;&nbsp;00:32:15&nbsp;&nbsp; LTE网络结构</p>
				</div>
			</div>
		</div>
	</div>
	<div class="row text-center">
		<%= link_to "本科作业", test_index_path, class: "btn btn-info btn-course", role: "button" %>
		<%= link_to "成绩查询", test_demand_path, class: "btn btn-info btn-course", role: "button" %>
	</div>
</div>

app/views/home/index.html.erb
<div class="container main-content">
	<!--carousel-->
	<div class="row" style="margin-bottom:20px;">
		<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				<li data-target="#carousel-example-generic" data-slide-to="2"></li>
			</ol>
			<!-- Wrapper for slides -->
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<%= image_tag "01index_image.png", alt:"1", class:"photo"%>
				</div>
			</div>
		</div>		
	</div>
	<!--网络设备维护-->
	<div class="video-name">
		<%= image_tag "01index_titleicon.png"%>
		<span class="num">1</span>
		<span>网络设备维护</span>
		<%= link_to "更多>>", "#", class:"more"%>
	</div>

	<div class="row" style="margin-bottom:20px;">
		<% (0..2).each do |index|%>
			<div class="col-md-4 col-xs-6 my-col">
				<%= link_to course_video1_path do %>
					<%=image_tag "01index_video1.png",class:"photo"%>
				<% end %>
				<div class="video-info">
					<div class="video-title">
						<h4 class="head">网络设备维护&nbsp;第一集</h4>
						<span class="para">维护的目的是保证设备处于最佳状态，满足业务晕性的需求……</span>
					</div>
					<div class="video-status">
					<span class="glyphicon glyphicon-time"></span>
					&nbsp;&nbsp;14天前
					<span class="status-right">
						<span class="glyphicon glyphicon-eye-open"></span>
						&nbsp;&nbsp;1496&nbsp;&nbsp;
						<span class="glyphicon glyphicon-heart"></span>
						&nbsp;&nbsp;0
					</span>
				</div>
			</div>
		</div>
	<% end %>
	</div>

	<!--网络优化-->
	<div class="video-name">
		<%= image_tag "01index_titleicon.png"%>
		<span class="num">2</span>
		<span>网络优化</span>
		<%= link_to "更多>>", "#", class:"more"%>
	</div>

	<div class="row"style="margin-bottom:20px;">
		<% (0..2).each do |index|%>
			<div class="col-md-4 col-xs-6 my-col">
				<%= link_to course_video2_path do %>
					<%=image_tag "video2.png",class:"photo"%>
				<% end %>
				<div class="video-info">
					<div class="video-title">
						<h4 class="head">网络设备维护&nbsp;第一集</h4>
						<span class="para">维护的目的是保证设备处于最佳状态，满足业务的需求……</span>
					</div>
					<div class="video-status">
					<span class="glyphicon glyphicon-time"></span>
					&nbsp;&nbsp;14天前
					<span class="status-right">
						<span class="glyphicon glyphicon-eye-open"></span>
						&nbsp;&nbsp;1496&nbsp;&nbsp;
						<span class="glyphicon glyphicon-heart"></span>
						&nbsp;&nbsp;0
					</span>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Education</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<!--in order to display signin page better -->
<div class="<%= "vbox" if params[:controller] == "signin"%>">
	<!--navbar-->
	<%= render partial:"share/topbar"%>

	<%= yield %>	
</div>
<!--footer-->
<div class="<%= "container" if params[:controller] != "signin"%>">
	<div class="<%= "row" if params[:controller] != "signin"%>">
		<div class="write-row"></div>
		<%= render partial: "share/footer"%>		
	</div>
</div>

</body>
</html>

app/views/share/_footer.html.erb
<div class="footer text-center">
	<%= link_to "关于我们", "#"%>
	<span>|</span>
	<%= link_to "联系我们", "#"%>
	<h5>Copyright © 2015大唐邦彦（上海）信息技术有限公司</h5>
</div>

app/views/share/_topbar.html.erb
<nav class="navbar navbar-default topbar">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "职 教 在 线", root_path, class:"navbar-brand title" %>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><%= image_tag "01index-en.png", class:"info" %></li>
			</ul>
			<form class="navbar-form navbar-right topform" role="search">
				<label class="sign" for="search">
					<span><%= link_to '登录', signin_index_path %></span> |
					<span><%= link_to '注册', signin_index_path %></span>
				</label><br>
				<div class="input-group">
					<input type="text" class="form-control">
					<span class="input-group-btn">
						<button class="btn btn-info" type="button">
							<span class="glyphicon glyphicon-search"></span>
						</button>
					</span>
				</div>
			</form>
		</div>
	</div>
</nav>
<div class="write-row"></div>

app/views/signin/index.html.erb
<div class="flex vbox signin-body">
	<div class="flex"></div>
	<div class="container">
		<div class="col-md- col-md-offset-7">
			<div class="signin-main">
				<div role="tabpanel">
					<!-- Nav tabs -->
					<ul class="nav nav-tabs" role="tablist">
						<li role="presentation" class="active sign-tab"><a href="#signin" role="tab" data-toggle="tab">登录</a></li>
						<li role="presentation" class="sign-tab"><a href="#signup" role="tab" data-toggle="tab">注册</a></li>
					</ul>
					<!-- Tab panes -->
					<div class="tab-content">
						<!--登录-->
						<div role="tabpanel" class="tab-pane sign-area active" id="signin">
							<form class="vbox">
								<div class="flex"></div>
								<div class="form-group" style="margin-bottom:30px;">
									<input type="email" class="form-control" id="exampleInputEmail1" placeholder="输入用户名">
								</div>
								<div class="form-group">
									<input type="password" class="form-control" id="exampleInputPassword1" placeholder="输入密码">
								</div>
								<div class="checkbox">
									<label>
										<input type="checkbox"> 下次自动登录
									</label>
									<%= link_to "忘记密码？", "#", class:"forget"%>
								</div>
								<div class="text-center">
									<button type="submit" class="btn btn-info btn-sign">登录</button>
								</div>
								<div class="flex"></div>
							</form>
						</div>
						<!--注册-->
						<div role="tabpanel" class="tab-pane sign-area" id="signup"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="flex"></div>
</div>	

app/views/teacher/result.html.erb
<!--成绩分布-->
<div class="container video-list main-content">
	<!--lessons-->
	<div class="list-title text-center">
		<span class="rel teacher-title">网络设备维护基础（2）成绩分布</span>
	</div>

	<div class="list-body">
		<!--学生成绩排名-->
		<div class="video-name">
			<%= image_tag "01index_titleicon.png"%>
			<span class="num">1</span>
			<span>学生设备维护</span>
		</div>
		<!--table-->
		<div class="table-responsive">
			<table class="table table-striped table-bordered">
			  	<thead class="thead-bgc">
			  		<tr>
			  			<th>学号</th>
			  			<th>姓名</th>
			  			<th>成绩</th>
			  			<% (1..10).each do |h_index|%>
			  				<th>题<%= h_index%></th>
			  			<% end %>
			  		</tr>
			  	</thead>
			  	<tbody>
			  		<% (1..10).each do |r_index|%>
				  		<tr>
				  			<th>20120018</th>
				  			<th>李静</th>
				  			<th>90</th>
				  			<% (1..10).each do |h_index|%>
				  				<th><%= h_index%></th>
				  			<% end %>
				  		</tr>
			  		<% end %>
			  	</tbody>
			</table>			
		</div>

		<!--选项分布表-->
		<div class="video-name">
			<%= image_tag "01index_titleicon.png"%>
			<span class="num">2</span>
			<span>选项分布表</span>
		</div>
		<!--table-->
		<div class="table-responsive">
			<table class="table table-striped table-bordered">
			  	<thead class="thead-bgc">
			  		<tr>
			  			<th>
			  				<span style="float:right;">题目</span><br>
			  				<span style="float:left;">统计项</span>
			  			</th>
			  			<% (1..10).each do |h_index|%>
			  				<th>题<%= h_index%></th>
			  			<% end %>
			  		</tr>
			  	</thead>
			  	<tbody>
			  		<% (1..7).each do |r_index|%>
				  		<tr>
				  			<th><%= @static_item["#{r_index}"]%></th>
				  			<% (1..10).each do |h_index|%>
				  				<th><%= h_index%></th>
				  			<% end %>
				  		</tr>
			  		<% end %>
			  	</tbody>
			</table>
		</div>
		<!--导出-->
		<div class="text-right">
			<button type="submit" class="btn btn-info btn-sign">导出为EXCEL</button>
		</div>
	</div>
</div>

app/views/teacher/test.html.erb
<!--test_background-->
<div class="demand-bg make-center">
	<div class="test-title text-center">
		<h1>成绩查询</h1>
	</div>	
</div>
<!--demand-->
<div class="container video-list">
	<!--lessons-->
	<div class="list-title">
		<span class="rel">&nbsp;&nbsp;课&nbsp;&nbsp;程&nbsp;&nbsp;</span>
	</div>
	<div class="list-body">
		<% (0..3).each do |lesson_index|%>
			<div class="checkbox">
				<h4><label><input type="checkbox" value="">网络设备维护基础（2）</label></h4>
			</div>
			<hr class="dot">
		<% end %>
	</div>
	<!--classes-->
	<div class="list-title">
		<span class="rel">&nbsp;&nbsp;班&nbsp;&nbsp;级&nbsp;&nbsp;</span>
	</div>
	<div class="list-body">
		<% (0..3).each do |class_index|%>
			<div class="checkbox">
				<h4><label><input type="checkbox" value="">2012级计算机（2）班</label></h4>
			</div>
			<hr class="dot">
		<% end %>
	</div>
	<div class="text-center">
		<%= button_to "查 询", teacher_result_path, class: "btn btn-info btn-course", method: :get %>
		<!-- <button type="submit" class="btn btn-info btn-course">查 询</button> -->
	</div>
</div>